services:
  - type: web
    name: my-ml-app  # <-- This is the service name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 10000